### ISSUE TITLE
Doesn't sync when editing on web editor

### ISSUE THREAD

**Issue by kyntk** [ryokat3/qiita-sync#60]
## What
When I edit artilce on web editor, the diff was not imported.

## Error

Process finished with exit code 1 on this line.
https://github.com/ryokat3/qiita-sync/blob/main/github_actions/qiita_sync_check.yml#L30

## How to resolve

The conditions here are probably the opposite.

```diff
-          [ ! -s "qiita_sync_output.txt" ] || exit 1
+          [ -s "qiita_sync_output.txt" ] || exit 1
```

or

```diff
-          [ ! -s "qiita_sync_output.txt" ] || exit 1
+          [ ! -s "qiita_sync_output.txt" ] && exit 1
```

I wasn't sure if you are accepting contributions, so I created this issue.

**Comment by ryokat3** [comment]
Hi kyntk,

Thank you for your report. I appreciate it very much. 

With the original condition `[ ! -s "qiita_sync_output.txt" ] || exit 1`, the GitHub action will run as

- if sync succeeds, then do nothing
- if sync fails, then exit 1

With the fixes you proposed, I think the behavior will be kind of opposite, and it will not trigger the sync.

This behavior (GitHub action will end up with error on next sync-check after editing articles on web editor, and the diff will not be imported) is an expected behavior for me, as of now. Instead, we can import the diff by manual synchronization described in README.

On the other hand, as you were annoyed with this behavior, I agree that this behavior is not the best.
Ideally, it's better that GitHub and Qiita are always automatically synced again even if not synched.

I would like to update the script to sync always and automatically if I get quite sure that it will not corrupt users' data in any cases. So, please let me know your opinion/thought/response if you have. もちろん日本語でもOKです。

**Comment by kyntk** [comment]
Hi ryokat3,

Thank you for the detailed explanation.

I had a misunderstanding about the behavior when editing on the web.
I'm going to try to consider ways to make synchronization easier in a safe way.

Thank you.
